image: "thlmylab/swakkd:stable"

stages:
  - prepare
  - build
  - restart
  - deploy

variables:
  APP_NAME: "SmartBite"
  DEPLOY: "yes"
  K8S_NAMESPACE: "webtech-ss2025-youssef-elkettani"
  DOMAIN: "edu.k8s.th-luebeck.dev"


prepare:
    stage: prepare
    rules:
      - if: '$DEPLOY == "yes"'
    script:
        - kubectl delete secret gitlab-registry-credentials || true
        - "kubectl create secret docker-registry gitlab-registry-credentials \
                    --docker-server=$CI_REGISTRY \
                    --docker-username=image-registry \ 
                    --docker-password=$CI_REGISTRY_TOKEN"
claim-volume:
    stage: prepare
    rules:
      - if: '$DEPLOY == "yes"'
    script:
      - kubectl apply -f deploy/storage/pvc.yaml

build-backend:
  stage: build
  rules:
    - if: '$DEPLOY == "yes"'
  script:
    - echo "🔨 Baue Backend Image..."
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --no-cache -t $CI_REGISTRY_IMAGE/backend:latest ./Backend
    - docker push $CI_REGISTRY_IMAGE/backend:latest
  image: docker:24.0
  services:
    - docker:24.0-dind

build-frontend:
  stage: build
  rules:
    - if: '$DEPLOY == "yes"'
  script:
    - echo "🔨 Baue Frontend Image..."
    - kubectl delete ingress smartbite-ingress -n $K8S_NAMESPACE || true
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --no-cache -t $CI_REGISTRY_IMAGE/frontend:latest ./app
    - docker push $CI_REGISTRY_IMAGE/frontend:latest
  image: docker:24.0
  services:
    - docker:24.0-dind


restart-services:
  stage: restart
  rules:
    - if: '$DEPLOY == "yes"'
  script:
    - kubectl apply -f deploy/storage/secret.yaml

    - kubectl apply -f deploy/storage/db_deployment.yaml
    - kubectl apply -f deploy/backend/backend_dep.yaml
    - kubectl apply -f deploy/frontend/app-dep.yaml

    - kubectl wait --for=condition=available deployment/db --timeout=300s
    - kubectl wait --for=condition=available deployment/backend --timeout=300s
    - kubectl wait --for=condition=available deployment/frontend --timeout=300s



deploy-backend:
  stage: deploy
  rules:
    - if: '$DEPLOY == "yes"'
  script:
    - mo deploy/backend/backend_dep.yaml | kubectl delete -f - || true
    - mo deploy/backend/backend_dep.yaml | kubectl apply -f -
    - mo deploy/backend/backend_service.yaml | kubectl apply -f -

deploy-frontend:
  stage: deploy
  rules:
    - if: '$DEPLOY == "yes"'
  script:
    - mo deploy/frontend/app-dep.yaml | kubectl delete -f - || true
    - mo deploy/frontend/app-dep.yaml | kubectl apply -f -
    - mo deploy/frontend/app-svc.yaml | kubectl apply -f -
    - HOST=uber-$CI_PROJECT_ID.$DOMAIN mo deploy/frontend/smartBite-ing.yaml | kubectl apply -f -

