image: "thlmylab/swakkd:stable"

stages:
  - prepare
  - build
  - test
  - deploy

variables:
  APP_NAME: "SmartBite"
  K8S_NAMESPACE: "webtech-ss2025-youssef-elkettani"
  DOMAIN: "edu.k8s.th-luebeck.dev"


prepare:
    stage: prepare
    script:
        - kubectl delete secret gitlab-registry-credentials || true
        - "kubectl create secret docker-registry gitlab-registry-credentials \
                    --docker-server=$CI_REGISTRY \
                    --docker-username=image-registry \ 
                    --docker-password=$CI_REGISTRY_TOKEN"
claim-volume:
    stage: prepare
    script:
      - kubectl apply -f deploy/storage/pvc.yaml

build-backend:
  stage: build
  script:
    - echo "🔨 Baue Backend Image..."
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/backend:latest ./Backend
    - docker push $CI_REGISTRY_IMAGE/backend:latest
  image: docker:24.0
  services:
    - docker:24.0-dind

build-frontend:
  stage: build
  script:
    - echo "🔨 Baue Frontend Image..."
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/frontend:latest ./app
    - docker push $CI_REGISTRY_IMAGE/frontend:latest
  image: docker:24.0
  services:
    - docker:24.0-dind

test-kubectl:
  stage: deploy
  script:
    - echo "Teste kubectl..."
    - kubectl version --client

deploy-backend:
  stage: deploy
  script:
    - kubectl apply -f deploy/backend/backend_deployment.yaml -n $K8S_NAMESPACE
    - kubectl apply -f deploy/backend/backend_service.yaml -n $K8S_NAMESPACE
    - kubectl rollout status deployment/backend -n $K8S_NAMESPACE --timeout=120s

deploy-frontend:
  stage: deploy
  script:
    - kubectl apply -f deploy/frontend/app-dep.yaml -n $K8S_NAMESPACE
    - kubectl apply -f deploy/frontend/app-svc.yaml -n $K8S_NAMESPACE
    - kubectl apply -f deploy/frontend/smartbite-ing.yaml -n $K8S_NAMESPACE
    - kubectl rollout status deployment/frontend -n $K8S_NAMESPACE --timeout=120s

#deploy-ingress:
#  stage: deploy
#
#  script:
#    - echo "🌐 Aktualisiere Ingress..."
#    - kubectl apply -f deploy/project-ing.yaml -n $K8S_NAMESPACE
 # only:
  #  - main