version: '3.9'

services:
  backend:
    build:
      context: ./Backend
    container_name: fastapi_backend
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Ysf@2002
      - POSTGRES_DB=postgres
      - DATABASE_URL=postgresql+psycopg2://postgres:${POSTGRES_PASSWORD}@db:5432/postgres
    image: git.mylab.th-luebeck.de:4181/webtech/ss2025/youssef-elkettani/backend:latest
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./app
    container_name: streamlit_frontend
    depends_on:
      - backend
    image: git.mylab.th-luebeck.de:4181/webtech/ss2025/youssef-elkettani/frontend:latest
    ports:
      - "8501:8501"

  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Ysf@2002
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
