apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: webtech-ss2025-youssef-elkettani
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: gitlab-registry-credentials
      containers:
        - name: backend
          image: git.mylab.th-luebeck.de:4181/webtech/ss2025/youssef-elkettani/backend:${IMAGE_TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_HOST
              value: "db"
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"