
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prime-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  rules:
  - host: "SmartBite-{{ CI_PROJECT_ID }}.edu.k8s.th-luebeck.dev"
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: prime-service
            port:
              number: 80
  tls:
  - secretName: prime-ingress-cert
    hosts: ["prime-{{ CI_PROJECT_ID }}.edu.k8s.th-luebeck.dev"]